### ISSUE TITLE
Pantalla de Login

### ISSUE THREAD

**Issue by megatichan** [abraham28s/PorMiTiendaApp#1]
@abraham28s @SantiagoMille 

- [x] Cuando Capturo el email y le doy en el keyboard en el boton de continuar no me pasa al campo del password 

- [x] No esta pasando la validacion hice el registro despues intente iniciar sesion con mi usuario y pasword y no me permitio el acceso

![screenshot_1517170210](https://user-images.githubusercontent.com/1206881/35486587-ad0b245a-0435-11e8-86a4-47077dcd1e0a.png)

**Comment by abraham28s** [comment]
La parte de focus al picar next ya quedo, la parte de la validación es por parte de WS, ya hable con Pablo para que lo regrese a la version funcional cuando quede solucionado cierro el issue

**Comment by abraham28s** [comment]
Fixed
