### ISSUE TITLE
Pantalla de Registro

### ISSUE THREAD

**Issue by megatichan** [abraham28s/PorMiTiendaApp#2]
@abraham28s @SantiagoMille 

- [x] El boton del continuar del keyboard no me brinca al siguiente caja de captura

- [x] No se muestra un procesando cuando se realiza el registro

- [x] Cuando se intenta registrar un usuario con un email existente envia mensaje de error en ingles hay que cambiarlo a español

![screenshot_1517169793](https://user-images.githubusercontent.com/1206881/35486476-3b1494fe-0434-11e8-90f0-678e4eb9505b.png)

**Comment by abraham28s** [comment]
Done
