### ISSUE TITLE
Diseño App Mobile

### ISSUE THREAD

**Issue by megatichan** [abraham28s/PorMiTiendaApp#5]
@abraham28s @SantiagoMille 

- [x] El nombre de la app cuando la instalas dice MenuActivity y no muestra el logo de PorMitienda

Aca les dejo tarjeta de trello donde pueden ver todas los screenshots de la app para que vean los temas de diseño que tienen que arreglar , no tengo contra que compararlo

https://trello.com/c/b9vxHROA

![screenshot_1517180700](https://user-images.githubusercontent.com/1206881/35488377-711755fa-044d-11e8-9167-e7810dc151a0.png)

**Comment by abraham28s** [comment]
Se tenia MenuActivity como pantalla inicial por motivos de pruebas, ya se corrigió.
